version: '3'
services:
  dynamo-db:
    build:
      context: ./databases/dynamo-db
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  redis-db:
    build:
      context: ./databases/redis-db
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=id_key
      - AWS_REGION=eu-west-1
      - AWS_SECRET_ACCESS_KEY=access_key
      - DYNAMO_ENDPOINT=database:8000
    ports:
      - "8001:8001"
    depends_on:
      - dynamo-db
    links:
      - dynamo-db
