version: '3.3'
services:
  dynamo-db:
    build:
      context: ./databases/dynamo-db
      dockerfile: Dockerfile
    ports:
      - "7000:8000"
  redis-db:
    build:
      context: ./databases/redis-db
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
  dynamodb-admin:
    build:
      context: ./ui/dynamodb-admin
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=id_key
      - AWS_REGION=eu-west-1
      - AWS_SECRET_ACCESS_KEY=access_key
      - DYNAMO_ENDPOINT=http://dynamo-db:8000
    ports:
      - "8801:8001"
    depends_on:
      - dynamo-db
    links:
      - dynamo-db
  redis-commander:
    build:
      context: ./ui/redis-commander
      dockerfile: Dockerfile
    command: --redis-host redis-db
    ports:
      - "8081:8881"
    depends_on:
      - redis-db
    links:
      - redis-db
